### ISSUE TITLE
Document Structure Continued (HTML lab)

### ISSUE THREAD

**Issue by wwchesson** [learn-co-curriculum/phase-0-html-document-structure-lab#11]
### Canvas Link

https://learning.flatironschool.com/courses/4968/assignments/151482?module_item_id=321603

### Concern

It was unclear how to structure the html code for this exercise. I did not know where to indent or how to order the syntax. In previous lessons, I felt like I was set up for success in how to write the code but here, there wasn't enough guidance.

**Comment by lizbur10** [comment]
Hi @wwchesson ! Thanks for posting this issue!

I have edited the lesson to clarify the instructions. Please note that the change will not be reflected in your Canvas course page, but it will be present for future cohorts of students. You can see the changes on the lab's GitHub page.

Thanks for contributing to the Flatiron School curriculum 💙
