### ISSUE TITLE
running bundle returns "Could not locate Gemfile"

### ISSUE THREAD

**Issue by JonnyOrtiz-source** [learn-co-curriculum/phase-0-html-document-structure-lab#15]
I forked and cloned the repo, then cd into phase-0-html-document-structure-lab.
I ran bundle as instructed and got "Could not locate Gemfile".
I suspect that I'll have to npm install, then npm test later.

jonnyortiz@Jonnys-Air phase-0-html-document-structure-lab % bundle
Could not locate Gemfile

**Comment by lizbur10** [comment]
Hi @JonnyOrtiz-source ! Yes, you're correct - the labs have all been updated to use mocha instead of rspec, so you'll need to run `npm install` and `npm test` instead. Apologies for the confusion! 💙
