### ISSUE TITLE
Document structuer

### ISSUE THREAD

**Issue by surjit446** [learn-co-curriculum/phase-0-html-document-structure-lab#28]
<!doctype html>
<htm "long en"l>
<head>
<title></title>

<body>
<h1>
<p>
</body>
</html>

**Comment by lizbur10** [comment]
Hi @surjit446 ! I'm not sure whether you intended to submit this comment as an issue so I'm going to go ahead and close it. Feel free to reopen if there's an issue you believe needs to be addressed. 💙
