### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cbrainy01** [learn-co-curriculum/phase-0-html-document-structure-lab#5]
Right above Recognize HTML elements there's a typo. I believe it should be "users" and not "uses".   : -

_'Google, for instance, can use the lang attribute to know when to prompt uses about translating web content.'_

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up there.

Thanks for contributing to the Flatiron School curriculum. 💙
