### ISSUE TITLE
readme not helpful

### ISSUE THREAD

**Issue by SumTrainer6** [learn-co-curriculum/phase-0-html-document-structure-lab#6]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.

## What should be changed?

Suggest your change here. Let us know what section or line of the Readme needs
to be updated, and any proposed corrections. Include the line number(s) if
possible.

## Additional context

readme was not very specific to the lesson and how to structure the test in a was that it needed to pass. it was more about giving info and not passing the assignment

**Comment by graciemcguire** [comment]
Hi @SumTrainer6 ! 
If you are struggling to pass an assignment, make sure you are running `rspec` to check what the tests are looking for! This is the best way to learn from, and pass the assignments at Flatiron.
Happy coding!
